# Generated by Django 6.0.4 on 2026-06-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_app', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursionrequest',
            name='confirmation_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Токен подтверждения'),
        ),
        migrations.AddField(
            model_name='excursionrequest',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтверждено'),
        ),
    ]
