# Generated by Django 6.0.4 on 2026-06-04 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum_app', '0003_excursionrequest_confirmation_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='excursionrequest',
            name='participants',
        ),
    ]
